# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main_window_v2.py'],
    pathex=[],
    # name 保持默认，PyInstaller 使用脚本名 main_window_v2
    binaries=[],
    datas=[
        ('assets/icon06_light.ico', 'assets'),
        ('assets/arrow_up.png', 'assets'),
        ('assets/arrow_down.png', 'assets'),
        ('assets/arrow_down2.png', 'assets'),
        ('assets/icon06_64x64_light.png', 'assets'),
        ('assets/icon14_64x64_dark.png', 'assets'),
        ('_ooxml_to_ssd.py', '.'),
        ('batch_processor.py', '.'),
        ('format_to_ssd.py', '.'),
        ('safe_shrink.py', '.'),
    ],
    hiddenimports=[
        'safe_shrink',
        'safe_shrink_gui',
        'batch_processor',
        'format_to_ssd',
        'sanitize_ssd',
        'ssd_embed_images',
        'sanitize_tab',
        'batch_tab',
        'slim_tab',
        'history_tab',
        'settings_tab',
        'theme_manager',
        'history_manager',
        'file_status',
        'translations',
        'docx',
        'pypdf',
        'PIL',
        'markitdown',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SafeShrink',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets/icon06_light.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='SafeShrink',
)
